---
bycon_definition_files:
  - config
  - filter_definitions
  - dataset_definitions
  - interval_definitions
  - handover_definitions
  - variant_definitions
defaults:
    genome_binning: 1Mb
dataset_ids:
  - progenetix
  - cellosaurus
  - 1000genomesDRAGEN
