---
bycon_definition_files:
  - config
  - filter_definitions
  - dataset_definitions
  - interval_definitions
  - handover_definitions
  - variant_definitions
  - remap_definitions
  - text_patterns
defaults:
    genome_binning: 1Mb
geosoft_root:
  - 
dataset_ids:
  - progenetix
  - cellosaurus
  - 1000genomesDRAGEN
refreshing:
  cnvstatistics:
    cnvcoverage: []
    delfraction: []
    cnvfraction: []
    delcoverage: []
    dupfraction: []
    dupcoverage: []

text_processing_scopes:
  grade:
    id: grade
    db_key: info.tumor_grade_text
    text_input: _input_grade
    error: _note_grade
    info_parameter: tumor_grade_text
    ontologized_parameter: tumor_grade
  stage:
    id: stage
    db_key: info.tumor_stage_text
    text_input: _input_stage
    error: _note_stage
    info_parameter: tumor_stage_text
    ontologized_parameter: pathological_stage
  tnm:
    id: tnm
    db_key: info.tumor_tnm_text
    text_input: _input_tnm
    error: _note_tnm
    info_parameter: tumor_tnm_text
    ontologized_parameter: pathological_tnm_findings
  survival:
    id: survival
    db_key: info.survival_status
    text_input: _input_survival
    error: _note_survival
    info_parameter: survival_status
    ontologized_parameter: survival_status

