---
bycon_definition_files:
  - config
  - filter_definitions
  - dataset_definitions
dataset_ids:
  - progenetix
data_collections:
  - biosamples
example_length: 5
map_types:
  ICD2UBERON:
    ontology_types:
      - icdot
      - UBERON
  ICDOntologies:
    ontology_types:
      - NCIT
      - icdom
      - icdot
    mappingfile:
      - rsrc
      - ICDOntologies.ods
