"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://progenetix.org/services/schemas/PublicationSampleCounts/v2021-04-13
title: Publication

meta:
  contributors:
    - description: "Michael Baudis"
      id: "orcid:0000-0002-9903-4248"
  provenance:
    - description: "Progenetix `bycon` project"
      id: 'https://github.com/progenetix/bycon/'
  used_by:
    - description: "Progenetix database schema (Beacon+ backend)"
      id: 'https://github.com/progenetix/schemas/'
  sb_status: community

description: >
  PublicationSampleCounts contains the count data for publication content, used
  for the Progenetix publications collection.

properties:

  ccgh:
    description: >
      The number of samples reported in this publication analyzed by chromosomal
      Comparative Genomic Hybridization (CGH)
    type: integer

  acgh:
    description: >
      The number of samples reported in this publication analyzed by any type
      of genomic hybridization array
    type: integer

  wes:
    description: >
      The number of samples reported in this publication analyzed by whole
      exome sequencing (WES)
    type: integer

  wgs:
    description: >
      The number of samples reported in this publication analyzed by whole
      genome sequencing (WGS)
    type: integer

  ngs:
    description: >
      The number of samples reported in this publication analyzed by any of
      WGS and/or WES. The number is at least the maximum of wes and wgs.
    type: integer

  genomes:
    description: >
      The number of samples reported in this publication analyzed. The number
      is at least the maximum of ccgh, acgh, wes, wgs.
    type: integer

  progenetix:
    description: >
      The number of samples from this publication in the Progenetix biosamples
      collection
    type: integer

