---
datasets:
  - id: arraymap
    name: arraymap
    identifier: 'org.progenetix::arraymap'
    description: "arraymap cancer CNV datasets"
    variantCount: 1
    assemblyId: 'GRCh38'
    createDateTime: 2012-01-01
    updateDateTime: 2019-10-01
    info:
      authorized: true
      accessType: PUBLIC
  - id: progenetix
    name: progenetix
    identifier: 'org.progenetix::progenetix'
    description: "Progenetix cancer genome profiles"
    variantCount: 1
    assemblyId: 'GRCh38'
    createDateTime: 2001-01-01
    updateDateTime: 2019-10-01
    info:
      authorized: true
      accessType: PUBLIC
  - id: cellosaurus
    name: cellosaurus
    identifier: 'org.progenetix::cellosaurus'
    description: "annotated cellosaurus cell line variants"
    variantCount: 1
    assemblyId: 'GRCh38'
    createDateTime: 2020-06-01
    updateDateTime: 2020-06-01
    info:
      authorized: true
      accessType: PUBLIC
  - id: dipg
    name: dipg
    identifier: 'org.progenetix::dipg'
    description: "DIPG data from publication Mackay et al., 2017"
    variantCount: 1
    assemblyId: 'GRCh38'
    createDateTime: 2015-01-01
    updateDateTime: 2017-10-01
    info:
      authorized: true
      accessType: PUBLIC
  - id: 'GRCh38:beacon_test2:2030-01-01'
    name: 'BeaconSpecTest2'
    identifier: 'org.progenetix::test2'
    description: "Beacon schema test"
    variantCount: 1
    assemblyId: 'GRCh38'
    createDateTime: 2019-01-01
    updateDateTime: 2019-10-01
    info:
      authorized: true
      accessType: PUBLIC
  - id: 'GRCh38:beacon_test:2030-01-01'
    name: 'BeaconSpecTest'
    identifier: 'org.progenetix::test'
    description: "Beacon schema test"
    variantCount: 1
    createDateTime: 2019-01-01
    updateDateTime: 2019-10-01
    assemblyId: 'GRCh38'
    info:
      authorized: true
      accessType: PUBLIC
