indexed_response_types:
  biosample:
    collection: biosamples
  individual:
    collection: individuals
  genomicVariant:
    collection: variants
  analysis:
    collection: analyses

indexed_special_collections:
  collations:
    id:
      db_key: id
    code:
      db_key: code
    child_terms:
      db_key: child_terms
    collation_type:
      db_key: collation_type
    scope:
      db_key: scope
    count:
      db_key: count
    code_matches:
      db_key: code_matches
  frequencymaps:
    id:
      db_key: id

indexed_special_dbs:
  cellz:
    biosamples:
      location:
        db_key: provenance.geo_location.geometry
        type: 2dsphere
    individuals:
      location:
        db_key: provenance.geo_location.geometry
        type: 2dsphere
    variants:
      id_aggregate:
        db_key:
          variant_state.id: 1
          location.sequence_id: 1
          location.start: 1
          location.end: 1
          info.var_length: 1
        type: compound
      variantbracketquery:
        db_key:
          variant_state.id: 1
          location.sequence_id: 1
          location.start: 1
          location.end: 1
          info.var_length: 1
        type: compound
      variantallelequery:
        db_key:
          location.sequence_id: 1
          location.start: 1
          sequence: 1
          reference_sequence: 1
        type: compound
      variantrangequery:
        db_key:
          location.sequence_id: 1
          location.start: 1
          location.end: 1
          variant_state.id: 1
          sequence: 1
        type: compound

  progenetix:
    biosamples:
      location:
        db_key: provenance.geo_location.geometry
        type: 2dsphere
    individuals:
      location:
        db_key: provenance.geo_location.geometry
        type: 2dsphere
    variants:
      variantbracketquery:
        db_key:
          variant_state.id: 1
          location.sequence_id: 1
          location.start: 1
          location.end: 1
          info.var_length: 1
        type: compound
      variantallelequery:
        db_key:
          location.sequence_id: 1
          location.start: 1
          sequence: 1
          reference_sequence: 1
        type: compound
      variantrangequery:
        db_key:
          location.sequence_id: 1
          location.start: 1
          location.end: 1
          variant_state.id: 1
          sequence: 1
        type: compound

  _byconHousekeepingDB:
    querybuffer:
      id:
        db_key: id
      target_count:
        db_key: target_count
    beaconinfo:
      date:
        db_key: date

  _byconServicesDB:
    genes:
      symbol:
        db_key: symbol
      synonyms:
        db_key: synonyms
      start:
        db_key: start
      end:
        db_key: end

    geolocs:
      id:
        db_key: id
      geoprov_city:
        db_key: geo_location.properties.city
      geoprov_country:
        db_key: geo_location.properties.country
      geoprov_iso_alpha3:
        db_key: geo_location.properties.ISO3166alpha3
      location:
        db_key: geo_location.geometry
        type: 2dsphere

    publications:
      id:
        db_key: id
      pubmedid:
        db_key: pubmedid
      ccgh_count:
        db_key: counts.ccgh
      acgh_count:
        db_key: counts.acgh
      wes_count:
        db_key: counts.wes
      wgs_count:
        db_key: counts.wgs
      genomes_count:
        db_key: counts.genomes
      geoprov_city:
        db_key: provenance.geo_location.properties.city
      geoprov_country:
        db_key: provenance.geo_location.properties.country
      geoprov_iso_alpha3:
        db_key: provenance.geo_location.properties.ISO3166alpha3
      location:
        db_key: provenance.geo_location.geometry
        type: 2dsphere


    ontologymaps:
      id:
        db_key: id
      code_group_id:
        db_key: code_group.id
      code_group_label:
        db_key: code_group.label






