format_patterns:

# local patterns
# TODO: adjust the internal ids w/ prefix

  - pattern: '^(?:pgx:)?(\w+bs-[\w\-\.]{4,128})$'
    link: '/biosample/?id='
    prepend_if_missing: ""

  - pattern: '^(?:pgx:)?(\w+cs-[\w\-\.]{4,128})$'
    link: '/callset/?id='
    prepend_if_missing: ""

  - pattern: '^(?:pgx:)?(\w+ind-[\w\-\.]{4,128})$'
    link: '/individual/?id='
    prepend_if_missing: ""

  - pattern: '^(?:pgx:)?(icdom-[\d]{1,5}(?:-\d{1,5})?)$'
    link: '/subset/?id='
    prepend_if_missing: "pgx:"

  - pattern: '^(?:pgx:)?(icdot-C\d\d?(?:\.\d)?)$'
    link: '/subset/?id='
    prepend_if_missing: "pgx:"

  - pattern: '^(?:pgx:)?(cohort-\w+)$'
    examples:
      - "pgx:cohort-TCGAcancers"
    link: '/subset/?id='
    prepend_if_missing: "pgx:"

# public prefix patterns (with possible underscore replacement)

  - pattern: '^(?:pgx:)?(NCIT:C\d{4,8})$'
    link: '/subset/?id='

  - pattern: '^(?:pgx:)?(PMID:\d{5,10})$'
    link: '/publication/?id='

  - pattern: '^(?:pgx:)?(cellosaurus:CVCL_[A-Z0-9]{4})$'
    examples:
      - cellosaurus:CVCL_0022
      - pgx:cellosaurus:CVCL_0022
    link: '/cellline/?id='

  - pattern: '^(?:pgx:)?(cbioportal:\w[\w\-]+?\w)$'
    examples:
      - cbioportal:prad_p1000
    link: '/subset/?id='

  - pattern: '^(?:pgx:)?(geo:G(?:PL|SE|DS)\d+)$'
    examples:
      - geo:GPL6801
    link: '/subset/?id='

  - pattern: '^(?:pgx:)?(geo:GSM\d+)$'
    examples:
      - geo:GSM491153
    link: '/biosample/?id='

