defaults:
  method: concise
  dataset_ids:
    - progenetix
  filters:
    - id: PMID
    - id: 'genomes:>0'
  filter_definitions:
    pgxuse:
      db_key: 'progenetix_use'
      scopes:
        publications:
          default: 1
      pattern: '^pgxuse\:(.+?)$'
      remove_prefix: true  
    PMID:
      name: "NCBI PubMed"
      url: "https://www.ncbi.nlm.nih.gov/pubmed/"
      db_key: 'id'
      scopes:
        publications:
          default: 1
      pattern: '^(PMID)(\:(\d+?))?$'
      examples:
        - 'PMID:28966033'
        - 'PMID:9405679'
      collation: datacollections
    wes:
      db_key: 'counts.wes'
      scopes:
        publications:
          default: 1
      pattern: '^wes\:([>=<]?\d+?)$'
      remove_prefix: true
    wgs:
      db_key: 'counts.wgs'
      scopes:
        publications:
          default: 1
      pattern: '^wgs\:([>=<]?\d+?)$'
      remove_prefix: true
    ccgh:
      db_key: 'counts.ccgh'
      scopes:
        publications:
          default: 1
      pattern: '^ccgh\:([>=<]?\d+?)$'
      remove_prefix: true
    acgh:
      db_key: 'counts.acgh'
      scopes:
        publications:
          default: 1
      pattern: '^acgh\:([>=<]?\d+?)$'
      remove_prefix: true
    genomes:
      db_key: 'counts.genomes'
      scopes:
        publications:
          default: 1
      pattern: '^genomes\:([>=<]?\d+?)$'
      remove_prefix: true
      examples:
        - 'genomes:>0'
    ngs:
      db_key: 'counts.ngs'
      scopes:
        publications:
          default: 1
      pattern: '^ngs\:([>=<]?\d+?)$'
      remove_prefix: true
    progenetix:
      db_key: 'counts.progenetix'
      scopes:
        publications:
          default: 1
      pattern: '^progenetix\:([>=<]?\d+?)$'
      remove_prefix: true
    arraymap:
      db_key: 'counts.arraymap'
      scopes:
        publications:
          default: 1
      pattern: '^arraymap\:([>=<]?\d+?)$'
      remove_prefix: true
method_keys:
  all: [ ] # forces empty list which is interpreted to use all
  counts:
    - id
    - counts
  concise:
    - id
    - label
    - journal
    - counts
    - authors
    - title
    - status
    - provenance
  details: []

