description: >-
  Each of the `concepts` defines the scope (individual, biosample, analysis),
  property to aggregate on, and optional `terms` or `splits` for selection
  or binning of the results in the returned `distribution`.

  Note: `sorted` right now only applies to the first dimension if used in 2D.

defaults:
  - - id: selectedHistologicalDiagnoses
    - id: sampleSex
  - - id: selectedCarcinomaDiagnoses
  - - id: selectedCarcinomaDiagnoses
    - id: sampleSex
  - - id: selectedPlatformTechnologies
  - - id: allPlatformTechnologies
  - - id: sampleAge
  - - id: sampleOriginDetails
    - id: sampleSex
  - - id: sampleICDO3histology
    - id: sampleAge
  - - id: sampleICDO3histology
    - id: sampleSex
  - - id: individualDisease
    - id: individualSex
  - - id: biosampleDisease
    - id: sampleSex
  - - id: sampleCountries
  - - id: individualAge
  - - id: individualAge
    - id: individualSex
  - - id: followupTime

$defs:

  selectedHistologicalDiagnoses:
    id: selectedHistologicalDiagnoses
    label: Selected Diagnostic Classes (by NCIT)
    scope: biosample
    property: biosample.histological_diagnosis.id
    terms:
      - id: NCIT:C9335
        label: Malignant neoplasm of breast
      - id: NCIT:C4863
        label: Prostate Carcinoma
      - id: NCIT:C9384
        label: Kidney Carcinoma
      - id: NCIT:C7431
        label: Malignant Ovarian Neoplasm
      - id: NCIT:C61574
        label: Malignant Uterine Corpus Neoplasm
      - id: NCIT:C9311
        label: Malignant Cervical Neoplasm
      - id: NCIT:C3513
        label:  Esophageal Carcinoma
      - id: NCIT:C35850
        label: Head and Neck Carcinoma
      - id: NCIT:C4878
        label: Lung Carcinoma
      - id: NCIT:C207229
        label: Pancreatic Carcinoma
      - id: NCIT:C4911
        label: Gastric Carcinoma
      - id: NCIT:C2955
        label: Colorectal Carcinoma
      - id: NCIT:C7927
        label: Liver Carcinoma
      - id: NCIT:C4822
        label: Malignant Glioma
      - id: NCIT:C3716
        label: Primitive Neuroectodermal Tumor
      - id: NCIT:C3224
        label: Melanoma
      - id: NCIT:C9118
        label: Sarcoma
      - id: NCIT:C4925
        label: Malignant Germ Cell Tumor
      - id: NCIT:C27753
        label: Acute Myeloid Leukemia, Not Otherwise Specified
      - id: NCIT:C3163
        label: Chronic Lymphocytic Leukemia
      - id: NCIT:C3466
        label: T-Cell Non-Hodgkin Lymphoma
      - id: NCIT:C3457
        label: B-Cell Non-Hodgkin Lymphoma

  selectedCarcinomaDiagnoses:
    id: selectedCarcinomaDiagnoses
    label: Selected Diagnostic Classes (carcinomas; by NCIT)
    description: >-
      Count of histological diagnoses in matched biosamples for selected carcinomas
    scope: biosample
    property: biosample.histological_diagnosis.id
    terms:
      - id: NCIT:C9384
        label: Kidney Carcinoma
      - id: NCIT:C3513
        label: Esophageal Carcinoma
      - id: NCIT:C35850
        label: Head and Neck Carcinoma
      - id: NCIT:C4878
        label: Lung Carcinoma
      - id: NCIT:C207229
        label: Pancreatic Carcinoma
      - id: NCIT:C4911
        label: Gastric Carcinoma
      - id: NCIT:C2955
        label: Colorectal Carcinoma
      - id: NCIT:C7927
        label: Liver Carcinoma

  selectedPlatformTechnologies:
    id: selectedPlatformTechnologies
    label: Selected Platform Technologies
    description: >-
      Count of basic platform technologies used in matched analyses
    scope: analysis
    property: analysis.platform_model.id
    terms:
      - id: EFO:0030075
        label: cDNA microarray
      - id: EFO:0010938
        label: large-insert clone DNA microarray
      - id: EFO:0010939
        label: oligonucleotide DNA microarray
      - id: EFO:0010937
        label: comparative genomic hybridization (CGH)
      - id: NCIT:C16437
        label: Chromosome Banding
      - id: OBI:0002117
        label: whole genome sequencing assay
      - id: OBI:0002118
        label: whole exome sequencing assay
      - id: NCIT:C158253
        label: Targeted Genome Sequencing

  allPlatformTechnologies:
    id: allPlatformTechnologies
    label: All Platforms by ID
    description: >-
      Count of basic platform technologies used in matched analyses
    scope: analysis
    property: analysis.platform_model.id

  sampleOriginDetails:
    id: sampleOriginDetails
    label: Anatomical Origin
    description: >-
      Count of anatomical sites in matched biosamples
    scope: biosample
    property: biosample.sample_origin_detail.id

  sampleSex:
    id: sampleSex
    label: Sex at birth
    description: >-
      Sex of the sample's donor
    scope: biosample
    property: biosample.individual_info.sex.id

  individualSex:
    id: individualSex
    label: Sex at birth
    description: >-
      Sex of the individual
    scope: individual
    property: individual.sex.id

  sampleICDO3histology:
    id: sampleICDO3histology
    label: ICD-O 3 Histology
    description: >-
      ICD-O 3 histologies in matched biosamples by age at diagnosis
    scope: biosample
    property: biosample.icdo_morphology.id

  sampleAge:
    id: sampleAge
    label: Age at sample collection
    description: >-
      Age at diagnosis (sample collection...)
    scope: biosample
    property: biosample.collection_moment
    format: iso8601duration
    splits:
      - value: P0D
        label: not yet born...
      - value: P18Y
        label: < 18 years
      - value: P40Y
        label: < 40 years
      - value: P65Y
        label: < 65 years
      - value: P80Y
        label: 65-80 years
      - value: P120Y
        label: 80+ years
    sorted: True

  individualAge:
    id: individualAge
    label: Individual's age at Diagnosis
    description: >-
      Individual's age at diagnosis
    scope: individual
    property: individual.index_disease.onset.age
    format: iso8601duration
    splits:
      - value: P0D
        label: not yet born...
      - value: P18M
        label: < 18 months
      - value: P18Y
        label: 1.5 to < 18 years
      - value: P40Y
        label: 18 to < 40 years
      - value: P65Y
        label: 40 to < 65 years
      - value: P80Y
        label: 65 to < 80 years
      - value: P120Y
        label: 80 years and older
    sorted: True

  individualDisease:
    id: individualDisease
    label: Diseases in Individuals
    description: 
      - Disease in matched individuals
    scope: individual
    property: individual.index_disease.disease_code.id

  biosampleDisease:
    id: biosampleDisease
    label: Diseases in Biosamples
    description: 
      - Disease in matched biosamples
    scope: biosample
    property: biosample.histological_diagnosis.id

  sampleCountries:
    id: sampleCountries
    label: Sample Countries
    label_key: country
    description: >-
      Count of countries of origin in matched biosamples
    scope: biosample
    property: biosample.geo_location.properties.ISO3166alpha3

  followupTime:
    id: followupTime
    label: Follow-up Time
    description: >-
      Follow-up time after diagnosis
    scope: individual
    property: individual.index_disease.followup
    format: iso8601duration
    splits:
      - value: P0D
        label: no value...
      - value: P6M
        label: < 6 months
      - value: P1Y
        label: < 1 year
      - value: P18M
        label: < 18 months
      - value: P3Y
        label: < 3 years
      - value: P5Y
        label: < 5 years
      - value: P10Y
        label: < 10 years
      - value: P100Y
        label: "> 10 years"
    sorted: True
