$schema: https://json-schema.org/draft/2020-12/schema
maturityAttributes:
  productionStatus: PROD
securityAttributes:
  defaultGranularity: record
  securityLevels:
    - PUBLIC
entryTypes:
  dataset:
    id: dataset
    name: Dataset
    ontologyTermForThisType:
      id: NCIT:C47824
      label: Data set
    partOfSpecification: Beacon v2.0.0
    description: A Dataset is a collection of related sets of information, e.g. genomic
      variations together with associated procedural and biological metadata. In a
      Beacon context, a datasets may consist of information generated in a specific
      study or project, or represent the main content of the Beacon resource.
    defaultSchema:
      id: dataset
      name: Default schema for datasets
      referenceToSchemaDefinition: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/models/json/beacon-v2-default-model/datasets/defaultSchema.json
      schemaVersion: v2.0.0
    aCollectionOf:
      - id: genomicVariant
        name: Genomic Variants
      - id: biosample
        name: Biosamples
      - id: individual
        name: Individuals
      - id: analysis
        name: Genomic Analyses
    additionalSupportedSchemas: []
  cohort:
    id: cohort
    name: Cohort
    ontologyTermForThisType:
      id: NCIT:C61512
      label: Cohort
    partOfSpecification: Beacon v2.0.0
    description: A group of individuals, identified by a common characteristic. [
      NCI ]
    defaultSchema:
      id: cohort
      name: Default schema for cohorts
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/cohort
      schemaVersion: v2.0.0
    aCollectionOf:
      - id: individual
        name: Individuals
    additionalSupportedSchemas: []
  genomicVariant:
    id: genomicVariant
    name: Genomic Variants
    ontologyTermForThisType:
      id: ENSGLOSSARY:0000092
      label: Variant
    partOfSpecification: Beacon v2.0.0
    description: The location of a sequence.
    defaultSchema:
      id: variant
      name: Default schema for a genomic variation
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/variant
      schemaVersion: v2.0.0
    additionallySupportedSchemas: []
  individual:
    id: individual
    name: Individual
    ontologyTermForThisType:
      id: NCIT:C25190
      label: Person
    partOfSpecification: Beacon v2.0.0
    description: A human being. It could be a Patient, a Tissue Donor, a Participant,
      a Human Study Subject, etc.
    defaultSchema:
      id: individual
      name: Default schema for an individual
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/individual
    additionallySupportedSchemas: []
  biosample:
    id: biosample
    name: Biological Sample
    ontologyTermForThisType:
      id: NCIT:C70699
      label: Biospecimen
    partOfSpecification: Beacon v2.0.0
    description: Any material sample taken from a biological entity for testing, diagnostic,
      propagation, treatment or research purposes, including a sample obtained from
      a living organism or taken from the biological object after halting of all its
      life functions. Biospecimen can contain one or more components including but
      not limited to cellular molecules, cells, tissues, organs, body fluids, embryos,
      and body excretory products. [ NCI ]
    defaultSchema:
      id: biosample
      name: Default schema for a biological sample
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/biosample
    additionallySupportedSchemas: []
  run:
    id: run
    name: Experimental run
    ontologyTermForThisType:
      id: NCIT:C148088
      label: Sequencing run
    partOfSpecification: Beacon v2.0.0
    description: The valid and completed operation of a high-throughput sequencing
      instrument for a single sequencing process. [ NCI ]
    defaultSchema:
      id: run
      name: Default schema for a sequencing run
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/run
      schemaVersion: v2.0.0
    additionallySupportedSchemas: []
  analysis:
    id: analysis
    name: Bioinformatics analysis of a genomic experiment
    ontologyTermForThisType:
      id: edam:operation_2945
      label: Analysis
    partOfSpecification: Beacon v2.0.0
    description: Apply analytical methods to existing data of a specific type.
    defaultSchema:
      id: analysis
      name: Default schema for a bioinformatics analysis
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/analysis
      schemaVersion: v2.0.0
    additionallySupportedSchemas: []
  phenopacket:
    id: phenopacket
    name: Phenopacket
    ontologyTermForThisType:
      id: NCIT:C25190
      label: Person
    partOfSpecification: BeaconPlus
    description: Information about a subject in phenopackets format
    defaultSchema:
      id: phenopacket
      name: Default schema for an phenopacket
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/phenopacket
    additionallySupportedSchemas: []
