"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://progenetix.org/services/schemas/BeaconInfoResponse/v2021-03-08
title: BeaconInfoResponse
meta:
  contributors:
    - description: "ELIXIR Beacon project team"
      id: "http://beacon-project.io"
    - description: "Michael Baudis"
      id: "orcid:0000-0002-9903-4248"
  provenance:
    - description: "Beacon v2"
      id: "https://github.com/ga4gh-beacon/specification-v2"
    - description: "Progenetix `bycon` project"
      id: 'https://github.com/progenetix/bycon/'
  used_by:
    - description: "Progenetix database schema (Beacon+ backend)"
      id: 'https://github.com/progenetix/schemas/'
  sb_status: community
description: >
  Response of a query over Beacon info. Use `InfoResponseContent` when querying the Beacon info endpoints, and `DatasetResponseContent` when querying the datasets endpoint.
type: object
required:
  - meta
  - response
properties:
  meta:
    $ref: 'BeaconInfoResponseMeta.yaml#/properties'
  response:
    oneOf:
      - $ref: 'BeaconInfoResponseContent.yaml#/properties'
      - $ref: 'BeaconDatasetResponseContent.yaml#/properties'
