defaults:
  query_fields:
    - symbol
    - ensembl_gene_ids
    - synonyms
  db: progenetix
  coll: genes
  response_entity_id: gene
meta:
  received_request_summary:
    requested_granularity: record
    assembly_id: GRCh38
    requested_schemas:
      - entity_type: gene
        schema: https://progenetix.org/services/schemas/ProgenetixGene
  returned_granularity: record
  info: >
    The main genes payload can be accessed in `response.results`.
assembly_ids:
  - GRCh38
method_keys:
  genespan:
    - symbol
    - reference_name
    - start
    - end
    - accession_version
    - cytobands
